### ISSUE TITLE
Undownloadable HALIUM_10 20230311 vendor image

### ISSUE THREAD

**Issue by JamiKettunen** [waydroid/OTA#2]
https://github.com/waydroid/OTA/commit/a76ebf983e48c70d97d8b744a55fb81038a8bf63 was made 14 hours ago (and is live @ https://ota.waydro.id/vendor/waydroid_arm64/HALIUM_10.json) but https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/ shows [`lineage-17.1-20230304-HALIUM_10-waydroid_arm64-vendor.zip`](https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/lineage-17.1-20230304-HALIUM_10-waydroid_arm64-vendor.zip/download) being the latest download still.

This results in being unable to `waydroid init` / `waydroid upgrade`:
<img src="https://user-images.githubusercontent.com/47358222/224478730-bc706de6-f6c4-4c9e-8d47-b4802923f702.png" width="240" />

If I may ask could the `append.py` (I presume that's what is used to add new entries) make sure the URL actually are valid and prevent it otherwise? I feel like some simple check like that could prevent stuff like this from happening again :)

**Comment by aleasto** [comment]
zapped

**Comment by hackur47** [comment]
Waiting for waydroid container service...
Binder node "vndbinder" for waydroid not found
plz answer me
